### ISSUE TITLE
No reaction from bot

### ISSUE THREAD

**Issue by ch4oz4ngel** [tama/pogo-discord-raid-bot#5] opened 2020-08-04 13:41 UTC
The bot starts but nothing happend for the commands 

(bot-env) root@59997-53573:/home/pogo-discord-raid-bot# python3 main.py
plugin.py
default.py
<class 'default.Default'>
{'default': <class 'default.Default'>}
648220935375290370 b'ch4oz' -> default
Connected !
b'@raidbot !summon'
b'<@736320274898878474> !summon'
b'<@736320274898878474> !raid'

**Comment by tama** [comment] 2020-08-05 12:08
My bad, the command is incorrect, the right one should be ```@RaidBot summon``` (without the "!")

**Comment by tama** [comment] 2020-08-12 12:44
Closing as there is no follow-up. Feel free to reopen if the issue is still present.

**Closed as completed by tama** 2020-08-12 12:44 UTC
